# Note: when updated the pre-built environments must be updated
# (run related robot in control-room and update values in getBaseAsZipBasename).
channels:
    - conda-forge

dependencies:
    - python=3.11.10 # https://pyreadiness.org/3.11/
    - uv=0.4.17 # https://github.com/astral-sh/uv/blob/main/CHANGELOG.md
    - pyyaml=6.0.2
    - ruamel.yaml=0.18.10
    - msgspec=0.19.0
    - pip:
          - robocorp-inspector==0.10.2 # https://github.com/robocorp/inspector/blob/master/CHANGELOG.md
          - playwright==1.52.0
          - tree-sitter==0.24.0
          - tree-sitter-yaml==0.7.0
          - sema4ai-http-helper==2.1.0
          - sema4ai-common==0.1.0
          - ruff==0.11.11
          - mcp==1.12.0
