# Note: when updated the pre-built environments must be updated
# (run related robot in control-room and update values in getBaseAsZipBasename).
channels:
    - conda-forge

dependencies:
    - python=3.11.10 # https://pyreadiness.org/3.11/
    - uv=0.4.17 # https://github.com/astral-sh/uv/blob/main/CHANGELOG.md
    - pyyaml=6.0.1
    - ruamel.yaml=0.18.6
    - msgspec=0.18.2
    - pip:
          - robocorp-inspector==0.10.2 # https://github.com/robocorp/inspector/blob/master/CHANGELOG.md
          - playwright==1.37.0
          - tree-sitter==0.22.3
          - tree-sitter-yaml==0.6.0
          - sema4ai-http-helper==1.0.2
