# Note: when updated the pre-built environments must be updated
# (run related robot in control-room and update values in getBaseAsZipBasename).
channels:
    - conda-forge

dependencies:
    - python=3.11.10 # https://pyreadiness.org/3.11/
    - uv=0.4.17 # https://github.com/astral-sh/uv/blob/main/CHANGELOG.md
    - pyyaml=6.0.2
    - ruamel.yaml=0.18.10
    - msgspec=0.19.0
    - python.app=1.4 # https://anaconda.org/conda-forge/python.app/files
    - pyscreeze==0.1.30 # VSCode Image Inspector dependency
    - python-mss==9.0.1 # VSCode Image Inspector dependency
    - pip:
          - playwright==1.37.0
          - tree-sitter==0.24.0
          - tree-sitter-yaml==0.7.0
          - sema4ai-http-helper==2.1.0

