# Note: when updated the pre-built environments must be updated
# (run related robot in control-room and update values in getBaseAsZipBasename).
channels:
    - conda-forge

dependencies:
    - python=3.10.12 # https://pyreadiness.org/3.10/
    - pip=23.3.2 # https://pip.pypa.io/en/stable/news/
    - pyyaml=6.0.1
    - msgspec=0.18.2
    - robocorp-truststore=0.8.0 # https://github.com/sethmlarson/truststore/blob/main/CHANGELOG.md
    - pip:
          - --use-feature=truststore
          - robocorp-inspector==0.10.2 # https://github.com/robocorp/inspector/blob/master/CHANGELOG.md
          - playwright==1.37.0
          - tree-sitter==0.22.3
          - tree-sitter-yaml==0.6.0
