# Note: when updated the pre-built environments must be updated
# (run related robot in control-room and update values in getBaseAsZipBasename).
channels:
    - conda-forge

dependencies:
    - python=3.11.10 # https://pyreadiness.org/3.10/
    - uv=0.4.17 # https://github.com/astral-sh/uv/blob/main/CHANGELOG.md
    - pyyaml=6.0.2
    - ruamel.yaml=0.18.10
    - msgspec=0.19.0
    - pywin32=303 # https://github.com/mhammond/pywin32/blob/main/CHANGES.txt
    - pyscreeze==0.1.30 # VSCode Image Inspector dependency
    - python-mss==9.0.1 # VSCode Image Inspector dependency
    - comtypes==1.2.1 # VSCode Windows Inspector dependency
    - psutil==5.9.8 # VSCode Windows Inspector dependency
    - java-access-bridge-wrapper==1.2.0 # VSCode Java Inspector dependency
    - pip:
          - playwright==1.37.0
          - tree-sitter==0.24.0
          - tree-sitter-yaml==0.7.0
          - sema4ai-http-helper==2.1.0
