# Note: when updated the pre-built environments must be updated
# (run related robot in control-room and update values in getBaseAsZipBasename).
channels:
    - conda-forge

dependencies:
    - python=3.10.12 # https://pyreadiness.org/3.10/
    - uv=0.2.37 # https://github.com/astral-sh/uv/blob/main/CHANGELOG.md
    - pyyaml=6.0.1
    - msgspec=0.18.2
    - python.app=1.3 # https://anaconda.org/conda-forge/python.app/files
    - pyscreeze==0.1.30 # VSCode Image Inspector dependency
    - python-mss==9.0.1 # VSCode Image Inspector dependency
    - pip:
          - playwright==1.37.0
