// Warning: Don't edit file (autogenerated from python -m dev codegen).

export const TREE_VIEW_CONTAINER_ROBOCORP_ROBOTS = "robocorp-robots";  // Sema4.ai Code
export const TREE_VIEW_ROBOCORP_TASK_PACKAGES_TREE = "robocorp-task-packages-tree";  // Sema4.ai Code
export const TREE_VIEW_ROBOCORP_PACKAGE_CONTENT_TREE = "robocorp-package-content-tree";  // Sema4.ai Code
export const TREE_VIEW_ROBOCORP_PACKAGE_RESOURCES_TREE = "robocorp-package-resources-tree";  // Sema4.ai Code
export const TREE_VIEW_ROBOCORP_CLOUD_TREE = "robocorp-cloud-tree";  // Sema4.ai Code