# Note: when updated the pre-built environments must be updated
# (run related robot in control-room and update values in getBaseAsZipBasename).
channels:
    - conda-forge

dependencies:
    - python=3.9.13
    - openssl>=3.0.7

    # https://pip.pypa.io/en/stable/news/
    - pip=22.1.2

    # https://anaconda.org/conda-forge/python.app/files
    - python.app=1.3

    - pip:
          - robocorp-inspector==0.8.4
          - robotframework==4.1
