name: Lint

on:
  - push
  - pull_request

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          
      - name: Setup node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          python -m pip install black==21.9b0
          
      - name: Install prettier
        run: |
          npm install -g prettier@2.4.1
          
      - name: TS Format Robot Framework LS (yarn prettier --write vscode-client/**/*.ts to format files locally)
        working-directory: ./robotframework-ls/
        run: prettier --check vscode-client/**/*.ts
        
      - name: Prettier Robocorp Code (yarn prettier --write vscode-client/**/*.ts to format files locally)
        working-directory: ./robocorp-code
        run: prettier --check vscode-client/**/*.ts
        
      - name: Prettier RF Interactive (yarn prettier --write src/**/*.{ts,tsx} to format files locally)
        working-directory: ./robotframework-interactive/vscode-interpreter-webview
        run: prettier --check src/**/*.{ts,tsx}
        
      - name: Black check robocorp-code
        run: |
          black --check ./robocorp-code --exclude=vendored
          
      - name: Black check robotframework-ls
        run: |
          black --check ./robotframework-ls --exclude=vendored
          
      - name: Black check robotframework-interactive
        run: |
          black --check ./robotframework-interactive --exclude=vendored
          
      - name: Black check robocorp-python-ls-core
        run: |
          black --check ./robocorp-python-ls-core --exclude=vendored --exclude=libs
