name: Lint

on:
  - push
  - pull_request

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pip deps
        run: |
          python -m pip install --upgrade pip fire poetry
          
          cd sema4ai-code
          
          poetry config virtualenvs.prefer-active-python true
          poetry install
          
      - name: Install prettier
        run: |
          npm install -g prettier@2.4.1
          
      - name: Prettier Sema4.ai Code (yarn prettier --write vscode-client/**/*.ts to format files locally)
        working-directory: ./sema4ai-code
        if: always()
        run: prettier --check vscode-client/**/*.ts
        
      - name: ruff format check sema4ai-code
        working-directory: ./sema4ai-code
        if: always()
        run: |
          echo $PWD
          ls -la
          # Fix with python -m dev ruff_format --format
          poetry run python -m dev ruff_format
          
      - name: mypy sema4ai-code
        if: always()
        working-directory: ./sema4ai-code
        run: |
          poetry run mypy --follow-imports=silent --show-column-numbers $PWD/src $PWD/tests $PWD/codegen

      - name: mypy sema4ai-python-ls-core
        if: always()
        working-directory: ./sema4ai-python-ls-core
        run: |
          poetry install
          poetry run mypy --follow-imports=silent --show-column-numbers $PWD/src $PWD/tests
                    
          