name: Lint

on:
  - push
  - pull_request

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pip deps
        run: |
          python -m pip install --upgrade pip fire poetry
          
          python -m venv .venv
          source ./.venv/bin/activate
          
          cd sema4ai-code
          
          poetry config virtualenvs.prefer-active-python true
          poetry install
          
          cd ..
          
          echo $PWD/sema4ai-code/src >> .venv/lib/python3.10/site-packages/rf_src.pth
          echo $PWD/sema4ai-python-ls-core/src >> .venv/lib/python3.10/site-packages/rf_src.pth
          echo $PWD/sema4ai-code/tests >> .venv/lib/python3.10/site-packages/rf_src.pth
          echo $PWD/sema4ai-python-ls-core/tests >> .venv/lib/python3.10/site-packages/rf_src.pth

          
      - name: Install prettier
        run: |
          npm install -g prettier@2.4.1
          
      - name: Prettier Sema4.ai Code (yarn prettier --write vscode-client/**/*.ts to format files locally)
        working-directory: ./sema4ai-code
        run: prettier --check vscode-client/**/*.ts
        
      - name: ruff format check sema4ai-code
        run: |
          echo $PWD
          ls -la
          source ./.venv/bin/activate
          ruff format --check ./sema4ai-code --exclude=vendored --exclude=_vendored
          
      - name: ruff format check sema4ai-python-ls-core
        run: |
          source ./.venv/bin/activate
          ruff format --check ./sema4ai-python-ls-core --exclude=vendored --exclude=libs
          
      - name: mypy sema4ai-code
        run: |
          source ./.venv/bin/activate
          mypy --follow-imports=silent --show-column-numbers $PWD/sema4ai-code/src $PWD/sema4ai-code/tests  $PWD/sema4ai-code/codegen

      - name: mypy sema4ai-python-ls-core
        run: |
          source ./.venv/bin/activate
          mypy --follow-imports=silent --show-column-numbers $PWD/sema4ai-python-ls-core/src $PWD/sema4ai-python-ls-core/tests
                    
          