name: Tests - RobotFramework Interactive (robotframework-interactive)

on:
  push:
    paths:
    - robotframework-interactive/**
    - robocorp-python-ls-core/**
    - .github/**

  pull_request:
    paths:
    - robotframework-interactive/**
    - robocorp-python-ls-core/**
    - .github/**
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        name: [
          "windows-py37-pip-v3",
#           "ubuntu-py38-master", TODO: Reenable when RF fixes https://github.com/robotframework/robotframework/issues/4607
          "ubuntu-py38-pip-v4",
        ]
        
        include:
          - name: "windows-py37-pip-v3"
            python: "3.7"
            os: windows-latest
#           - name: "ubuntu-py38-master" TODO: Reenable when RF fixes https://github.com/robotframework/robotframework/issues/4607
#             python: "3.8"
#             os: ubuntu-latest
          - name: "ubuntu-py38-pip-v4"
            python: "3.8"
            os: ubuntu-latest


    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install robotframework from master
      run: python -W ignore -m pip install https://github.com/robotframework/robotframework/archive/master.zip --no-warn-script-location --disable-pip-version-check
      if: contains(matrix.name, '-master')
    - name: Install robotframework from pip
      run: python -W ignore -m pip install "robotframework>=3.2,<4.0"
      if: contains(matrix.name, '-pip-v3')
    - name: Install robotframework from pip
      run: python -W ignore -m pip install "robotframework>=4.0"
      if: contains(matrix.name, '-pip-v4')
    - name: setup.py install (robocorp-pytho-ls-core)
      working-directory: ./robocorp-python-ls-core
      run: |
        cd src
        python setup.py install
        cd ..
    - name: setup.py install
      working-directory: ./robotframework-interactive
      run: |
        cd src
        python setup.py install
        cd ..
    - name: Install test deps
      working-directory: ./robotframework-interactive
      run: |
        cd tests
        pip install -r test_requirements.txt
        cd ..
    - name: Test
      working-directory: ./robotframework-interactive/tests
      env:
        PYTHONPATH: .
        RUN_TESTS_TIMEOUT: 300
      run: python -u ../../robocorp-python-ls-core/tests/run_tests.py -rfE -otests_output -vv .
    - uses: actions/upload-artifact@v1
      with:
        name: tests_output.${{ matrix.name }}.txt
        path: robotframework-interactive/tests/tests_output

