name: Tests - Sema4.ai Code (sema4ai-code)

on:
  push:
    paths:
    - sema4ai-code/**
    - sema4ai-python-ls-core/**
    - .github/**

  pull_request:
    paths:
    - sema4ai-code/**
    - sema4ai-python-ls-core/**
    - .github/**
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        name: [
          "ubuntu-py310",
          "windows-py310",
#           "mac-py310", mac disabled because it takes too long for runners to pick the mac job up.
        ]
        
        include:
          - name: "ubuntu-py310"
            python: "3.10"
            os: ubuntu-latest
          - name: "windows-py310"
            python: "3.10"
            os: windows-latest
#           - name: "mac-py310"
#             python: "3.10"
#             os: mac-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Vendor robocorp_ls_core
      working-directory: ./sema4ai-code
      run: |
        pip install fire poetry
        python -m dev vendor-robocorp-ls-core
    - name: setup.py install
      working-directory: ./sema4ai-code
      run: poetry install
    - name: Test
      working-directory: ./sema4ai-code/tests
      env:
        PYTHONPATH: .
        CI_CREDENTIALS: ${{ secrets.CI_CREDENTIALS }}
        CI_ENDPOINT: ${{ secrets.CI_ENDPOINT }}
        # Big timeout to create environment in windows.
        RUN_TESTS_TIMEOUT: 3000
      run: poetry run python -u ../../sema4ai-python-ls-core/tests/run_tests.py -rfE -otests_output -vv .
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: tests_output.${{ matrix.name }}.txt
        path: sema4ai-code/tests/tests_output
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: log.${{ matrix.name }}.html
        path: sema4ai-code/tests/output/log.html

