name: Tests - Robocode VSCode (robocode-vscode)

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        name: [
          "ubuntu-py38",
        ]
        
        include:
          - name: "ubuntu-py38"
            python: "3.8"
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Vendor robocode_ls_core
      working-directory: ./robocode-vscode
      run: |
        pip install fire
        python -m dev vendor-robocode-ls-core
    - name: setup.py install
      working-directory: ./robocode-vscode
      run: |
        cd src
        python setup.py install
        cd ..
    - name: Install test deps
      working-directory: ./robocode-vscode
      run: |
        cd tests
        pip install -r test_requirements.txt
        cd ..
    - name: Test
      working-directory: ./robocode-vscode/tests
      env:
        PYTHONPATH: .
      run: python -u ../../robocode-python-ls-core/tests/run_tests.py -otests_output -vv .
    - uses: actions/upload-artifact@v1
      with:
        name: tests_output.${{ matrix.name }}.txt
        path: robocode-vscode/tests/tests_output

